#! /usr/bin/env bash

function install-dir () {
  local dir="${1:?Missing directory}"

  pip install -r "$dir/requirements.txt" -t ./src/vendor --upgrade
}


install-dir ./src
install-dir ./functions/custom_resources
install-dir ./src/OrderService
install-dir ./src/ProductService
install-dir ./functions/Resources